export const Data = [
  { pizza: 'Minh', amount: 2, prize: 75 },
  { pizza: 'otoke piza', amount: 4, prize: 160 },
  { pizza: 'otoke piza', amount: 6, prize: 1603 },
  { pizza: 'pizfired', amount: 1, prize: 35 },
  { pizza: 'picong', amount: 2, prize: 110 },
  { pizza: 'pizito', amount: 8, prize: 1650 },
  { pizza: 'pizza machito', amount: 4, prize: 160 },
  { pizza: 'pitoza', amount: 4, prize: 190 },
  { pizza: 'pizzzto', amount: 2, prize: 130 },
  { pizza: 'pizabigmom', amount: 4, prize: 160 },
  { pizza: 'pizkaido', amount: 4, prize: 160 },
  { pizza: 'pizoro', amount: 4, prize: 160 },
  { pizza: 'pizza luffy', amount: 4, prize: 160 },
  { pizza: 'pizkaito', amount: 4, prize: 160 },
  { pizza: 'pizza machito', amount: 4, prize: 160 },
  { pizza: 'pizfired ito', amount: 4, prize: 160 },
  { pizza: 'pizza kaisen', amount: 10, prize: 2600 },
  { pizza: 'hot combo', amount: 1, prize: 160 },
  { pizza: 'pizza pluto', amount: 4, prize: 160 },
]
